name: movie_app
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  easy_localization: ^3.0.8
  carousel_slider: ^5.1.1
  provider: ^6.1.5+1
  google_sign_in: ^6.1.0
  #api packages
  dio: ^5.9.0
  talker_dio_logger: ^5.0.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner:

flutter:

  uses-material-design: true


  assets:
   - assets/images/
   - assets/translations/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
